### ISSUE TITLE
Scalling my Existing DOT.NET 2.1 with Piranha Blog

### ISSUE THREAD

**Issue by webzest** [PiranhaCMS/piranha.core.examples#1]
I cloned the example into VS2017 and launched to get a feel for it.  I was not able to use the login to navigate to the Admin area.
I also changed the SQLLite to SQLServer with my own SQL Server database.  The example photo is not getting loaded.
I like the idea of incorporating a BLOG into my existing DOT.NET 2.1 App, just like any other PHP WordPress.  Piranha has the potential to provide this scaling process for the Default Visual Studio MVC Template with Authentication.  My Existing App was built on the MVC Template.  With additional enhancements that I was able to figure out and added in, I have a nice working platform that is now easy to maintain and publish, as needed.  Additionally, I am using this app to display my Photography Portfolio and to also generate my invoices and Estimates for my clients.  
I would love to add a Blog component to it, utilizing the existing User/Identity Management Middleware Framework.  If you have the time and patience to collaborate with an eager to learn .NET App Newbie, I am willing and able to follow guidance and instructions to add Piranha to my existing App as a GREAT plug-in or add-on.

**Comment by tidyui** [comment]
You’re right! I forgot to add any claims to the admin user :) I’ll update the example!

**Comment by tidyui** [comment]
I've updated the example so you log into the manager area. I've you need any more help, please open a    separate issue per question so I know what to answer!

Regards
